### ISSUE TITLE
For login emails, set send name as "Open Access Button"

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#332]
Same as we have done with other emails

**Comment by markmacgillivray** [comment]
Done.

**Comment by JosephMcArthur** [comment]
still seeing this

![image](https://cloud.githubusercontent.com/assets/4953703/19626476/096afae4-992b-11e6-99a2-82b63622ff76.png)

Quite possible my inbox is just remembering the name admin though. @svmelton @natalianorori can you do a quick test?

**Comment by markmacgillivray** [comment]
Sorry, fixed - I accidentally set it against the old ODB settings, not OAB, and I had an email from the admin system showing the expected value so thought it was working. Works now.
