### ISSUE TITLE
Emailing from request system doesn't replace variables or copy across email of author

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#378]
Figured out the workflow now, but I can't get it to work as described.

**Comment by JosephMcArthur** [comment]
Tried it on a couple of requests, including:
* http://oab.test.cottagelabs.com/request/T4hokmZdzGBASGsvK
* http://oab.test.cottagelabs.com/request/3u3xARjRsQoJzeniZ

**Comment by markmacgillivray** [comment]
Yes this seems to have stopped working. Will check tomorrow.

**Comment by JosephMcArthur** [comment]
It's working again??? and it's wonderful.

**Comment by JosephMcArthur** [comment]
Still fairly inconsistent, doesn't work here http://oab.test.cottagelabs.com/request/3RYnBAuWjk9MmhNSY

**Comment by markmacgillivray** [comment]
This should be fixed now - click the email button from a request when you are admin. It takes you to the admin area and pops the email area open. Select a template - you should see the content of the template in the box. Then below the box there should be a light blue button that you can click to populate the template with the variables relevant to the request you were viewing. Hit it and the content area should change and if it can have an html email generated from it then you will see the html-formatted content below the content box too.

You will also see the email addresses of the request creator and the request author contact address just BELOW the TO box - it does not insert them both, because it does not know which one you want to email, this can be changed later, but for now to ensure we don't accidentally email the wrong people, it does it this way. Then you can just copy/paste the email address that you want into the box (or write in your own, or whatever email address you want to use to test). Then if you send the email you should receive it (if you put your own address in to test) and it should look populated.

You can also reselect a different template if you changed your mind before sending - then it will change the content and the blue "populate" button can be used again. So you can try different ones.

Let me know if this works now, and if so close the issue.

**Comment by JosephMcArthur** [comment]
It still doesn't work for the request I gave above. However, it does work in other cases e.g http://oab.test.cottagelabs.com/request/kdFZe93596WNfC65u

**Comment by markmacgillivray** [comment]
Ah, the one that you linked to that doesn't work is one of the old ones - the user account for it is a user on the live system, and there is no matching user account on the dev system.

I can add a catch for that, so that if it is tried on a request from a user who does not have an account (which may be possible once we import all the old blocks as requests) then it will not just fail to work - however, we would still have the problem that we may not have all the variables necessary to populate the email in all cases, so some manual tidying would be required.

**Comment by markmacgillivray** [comment]
Done as described above, as done as it is possible to be.
