### ISSUE TITLE
The buttons on the side menu on about and support page don't match changes in the page. 

### ISSUE THREAD

**Issue by alexgiann** [OAButton/backend#91]
The buttons on the side menu on the about page [https://openaccessbutton.org/about] and the support us page [https://openaccessbutton.org/support] are not matching the changes in the page when you click through them. 

Example: I can click on the "volunteer" button and get the text but the page is not changed. I can however manually add the page https://openaccessbutton.org/support/ [#volunteer] and it works (although it does always take me to the middle of the page.

**Comment by JosephMcArthur** [comment]
Think I've fixed this in /about. @alexgiann can you verify this?

**Comment by alexgiann** [comment]
Nope. Still not getting the proper link when I click through the side menu. I tried it on different browsers too (+incognito) but nothing changed. :( @JosephMcArthur

**Comment by JosephMcArthur** [comment]
Gah, I confused this with another bug. Okay, haven't fixed this!

**Comment by mtb-za** [comment]
Just to clarify, this is to do with updating the URL when clicked?

Right now, this is expected behaviour, but I can probably change it. Just need to look where and how.

**Comment by JosephMcArthur** [comment]
Yes, that's how I've understood it. Would be good for the URL to change on
click.

On 23 February 2016 at 09:02, Martin Bentley <notifications@github.com>
wrote:

> Just to clarify, this is to do with updating the URL when clicked?
>
> Right now, this is expected behaviour, but I can probably change it. Just
> need to look where and how.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/91#issuecomment-187608075>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment]
It now changes on click.

@alexgiann: Please reopen this if I have misunderstood this.

**Comment by mtb-za** [comment]
Duplicate of #60.

**Comment by mtb-za** [comment]
So something broke badly on these earlier. This is just a note that we are never touching these pages *ever* again.
